### ISSUE TITLE
hasSemiTransparency  add to opts

### ISSUE THREAD

**Issue by 3400442579** [mcychan/PnnQuant.js#3]
hasSemiTransparency  add to opts ,Manual control output type PNG / gif.

**Comment by mcychan** [comment]
I'm lazy to redesign the responsive web layout.
Thanks omggif for providing gif encoding.
It will graceful fallback to output png when there is any error of the above library occurs.

Output png only: https://mcychan.github.io/PnnQuant.js/demo/index.html?png
