### ISSUE TITLE
transparency  image save  gif file , dither=true ，The transparent one becomes opaque

### ISSUE THREAD

**Issue by 3400442579** [mcychan/PnnQuant.js#6]
Original：
![01a](https://user-images.githubusercontent.com/34226979/113236228-1271bd80-92d7-11eb-9730-b5b797dd0e08.png)

Output：
![a](https://user-images.githubusercontent.com/34226979/113236283-2a494180-92d7-11eb-9928-ec673a4a1956.gif)

compare：
![未命名](https://user-images.githubusercontent.com/34226979/113237042-b445da00-92d8-11eb-919c-da9432483fd4.png)

**Comment by mcychan** [comment]
![gg](https://user-images.githubusercontent.com/26831069/113243237-389e5a00-92e5-11eb-986d-f2c40801082f.png)
The above image contains semi transparent pixels and I marked them as pink color (alpha < 255 and alpha > 0 => alpha = 255)

Solution: add opts.alphaThreshold = 254;
![gg](https://user-images.githubusercontent.com/26831069/113243392-8024e600-92e5-11eb-8bbd-a1e846aa9241.gif)

**Comment by mcychan** [comment]
![yg](https://user-images.githubusercontent.com/26831069/114333254-73707f80-9b7a-11eb-9e8c-afa74f0f2bc2.gif)
